require('dotenv').config();
const express=require('express'); const path=require('path'); const crypto=require('crypto'); const fs=require('fs'); const multer=require('multer'); const pdfParse=require('pdf-parse'); const Tesseract=require('tesseract.js'); const PDFDocument=require('pdfkit'); const {execFile}=require('child_process'); const db=require('./platform-db');
const app=express(); const PORT=Number(process.env.PORT)||3000; const PUBLIC=path.join(__dirname,'public');
app.use(express.json({limit:'3mb'})); app.use(express.urlencoded({extended:true})); app.use(express.static(PUBLIC));
function cookieToken(req){const m=String(req.headers.cookie||'').match(/(?:^|;)\s*dm_token=([^;]+)/);return m?decodeURIComponent(m[1]):''}
async function auth(req,res,next){try{const s=await db.session(cookieToken(req));if(!s)return res.status(401).json({error:'Login required'});req.session=s;req.businessId=s.business_id;req.userId=s.user_id;next()}catch(e){res.status(500).json({error:e.message})}}
function csrf(req,res,next){if(['GET','HEAD','OPTIONS'].includes(req.method))return next();const c=String(req.headers['x-csrf-token']||'');if(!c)return res.status(403).json({error:'CSRF token missing'});db.get('SELECT csrf_hash FROM sessions WHERE token_hash=?',[crypto.createHash('sha256').update(cookieToken(req)).digest('hex')]).then(s=>{if(!s||s.csrf_hash!==crypto.createHash('sha256').update(c).digest('hex'))return res.status(403).json({error:'Invalid CSRF token'});next()}).catch(e=>res.status(500).json({error:e.message}))}
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:12*1024*1024},fileFilter:(r,f,cb)=>cb(null,['application/pdf','image/jpeg','image/png','image/webp'].includes(f.mimetype))});
function hash(buf){return crypto.createHash('sha256').update(buf).digest('hex')}
async function ocrImage(buf){const r=await Tesseract.recognize(buf,'eng',{logger:x=>{if(x.status==='recognizing text'&&Math.round((x.progress||0)*100)%20===0)console.log('OCR',Math.round((x.progress||0)*100)+'%')}});return r.data.text||''}
function pdfToPng(buf){return new Promise((resolve,reject)=>{const dir=path.join(__dirname,'data','ocr');fs.mkdirSync(dir,{recursive:true});const base=path.join(dir,'scan-'+Date.now());const pdf=base+'.pdf';fs.writeFileSync(pdf,buf);execFile('pdftoppm',['-png','-f','1','-singlefile','-r','180',pdf,base],async e=>{try{fs.rmSync(pdf,{force:true});if(e)throw e;const p=base+'.png';const b=fs.readFileSync(p);fs.rmSync(p,{force:true});resolve(b)}catch(x){reject(x)}})})}
async function extractText(file){if(file.mimetype!=='application/pdf')return ocrImage(file.buffer);let text='';try{text=(await pdfParse(file.buffer)).text||''}catch{}if(text.trim().length>80)return text;try{return await ocrImage(await pdfToPng(file.buffer))}catch{return text}}
function cleanLines(t){return String(t||'').split(/\r?\n/).map(x=>x.replace(/\s+/g,' ').trim()).filter(Boolean)}
function firstMatch(lines,patterns){for(const l of lines)for(const p of patterns){const m=l.match(p);if(m)return m[1].trim()}return ''}
function parseBill(text){const lines=cleanLines(text);let supplier=firstMatch(lines,[/^M\/S\.?\s+(.+)/i,/^For\s+(.+)/i,/^Firm\s*[:\-]\s*(.+)/i]);let invoiceNo=firstMatch(lines,[/Invoice\s*No\.?\s*[:\-]?\s*([A-Z0-9\/-]+)/i,/Invoice\s*Number\s*[:\-]?\s*([A-Z0-9\/-]+)/i]);let invoiceDate=firstMatch(lines,[/Invoice\s*Date\s*[:\-]?\s*([0-9A-Za-z\/-]+)/i]);let gstin=firstMatch(lines,[/GSTIN\s*[:\-]?\s*([0-9A-Z]{15})/i]);let pos=firstMatch(lines,[/Place\s*of\s*Supply\s*[:\-]?\s*(.+)/i]);const items=[];for(let i=0;i<lines.length;i++){const l=lines[i];if(!/\b(8302|HSN|SAC)\b/i.test(l)&&!/\b\d+\s+(NOS|PCS|PC|BOX|SET|KG|LTR|M)\b/i.test(l))continue;const m=l.match(/^(?:\d+[.)]?\s+)?(.+?)\s+(\d{3,8})\s+(\d+(?:\.\d+)?)\s*(NOS|PCS|PC|BOX|SET|KG|LTR|M|PACK)?\s+(?:₹|Rs\.?|INR)?\s*([\d,]+(?:\.\d+)?)\s+(?:[\d,]+(?:\.\d+)?\s+)?(?:IGST|CGST|SGST)?\s*(\d+(?:\.\d+)?)?%?/i);if(m){const name=m[1].trim();if(name.length>2&&!/total|amount|taxable|invoice/i.test(name)){items.push({name,hsn_code:m[2],quantity:Number(m[3]),unit:(m[4]||'PCS').toUpperCase(),purchase_price:Number(m[5].replace(/,/g,'')),gst_rate:Number(m[6]||0),taxable_value:Number(m[5].replace(/,/g,''))*Number(m[3]),tax_amount:0,line_total:Number(m[5].replace(/,/g,''))*Number(m[3])})}}}if(!items.length){for(const l of lines){const m=l.match(/^(.+?)\s+(\d+(?:\.\d+)?)\s*(PCS|NOS|PC|BOX|SET|KG|LTR|M)?\s+(?:₹|Rs\.?|INR)?\s*([\d,]+(?:\.\d+)?)$/i);if(m&&!/total|amount|tax/i.test(m[1]))items.push({name:m[1],quantity:Number(m[2]),unit:(m[3]||'PCS').toUpperCase(),purchase_price:Number(m[4].replace(/,/g,'')),gst_rate:0,hsn_code:'',taxable_value:Number(m[4].replace(/,/g,''))*Number(m[2]),tax_amount:0,line_total:Number(m[4].replace(/,/g,''))*Number(m[2])})}}return {supplier_name:supplier,supplier_gstin:gstin,invoice_number:invoiceNo,invoice_date:invoiceDate,place_of_supply:pos,items,raw_text:text}}
function words(n){n=Math.round(Number(n)||0);const a=['','One','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Eleven','Twelve','Thirteen','Fourteen','Fifteen','Sixteen','Seventeen','Eighteen','Nineteen'],b=['','','Twenty','Thirty','Forty','Fifty','Sixty','Seventy','Eighty','Ninety'];function x(v){if(v<20)return a[v];if(v<100)return b[Math.floor(v/10)]+' '+a[v%10];if(v<1000)return a[Math.floor(v/100)]+' Hundred '+x(v%100);if(v<100000)return x(Math.floor(v/1000))+' Thousand '+x(v%1000);if(v<10000000)return x(Math.floor(v/100000))+' Lakh '+x(v%100000);return x(Math.floor(v/10000000))+' Crore '+x(v%10000000)}return (x(n).replace(/\s+/g,' ').trim()||'Zero')+' Rupees Only'}
function pdfInvoice(res,title,biz,inv){const doc=new PDFDocument({size:'A4',margin:35});res.setHeader('Content-Type','application/pdf');res.setHeader('Content-Disposition','attachment; filename="'+title+'.pdf"');doc.pipe(res);doc.fontSize(16).text('TAX INVOICE',{align:'center'}).fontSize(9).text('ORIGINAL FOR RECIPIENT',{align:'center'}).moveDown();doc.fontSize(13).text(biz.name||'Business',{align:'center'}).fontSize(8).text((biz.address||'')+' | GSTIN: '+(biz.gstin||'-'),{align:'center'}).moveDown();doc.fontSize(9).text('Customer: '+(inv.customer_name||'-'));doc.text('Address: '+(inv.customer_address||'-'));doc.text('GSTIN: '+(inv.customer_gstin||'-'));doc.text('Invoice No: '+inv.invoice_no+'    Date: '+inv.invoice_date);doc.text('Place of Supply: '+(inv.place_of_supply||inv.customer_state||'-'));doc.moveDown();doc.fontSize(8).text('Sr | Product | HSN | Qty | Rate | Taxable | GST | Total');doc.moveTo(35,doc.y+2).lineTo(560,doc.y+2).stroke();doc.moveDown(6);inv.items.forEach((x,i)=>{doc.text((i+1)+' | '+x.item_name+' | '+(x.hsn_code||'-')+' | '+x.quantity+' '+x.unit+' | '+x.rate.toFixed(2)+' | '+x.taxable_value.toFixed(2)+' | '+x.total_tax.toFixed(2)+' | '+x.line_total.toFixed(2));doc.moveDown(4)});doc.moveDown().text('Taxable Amount: '+Number(inv.subtotal).toFixed(2));doc.text('CGST: '+Number(inv.cgst).toFixed(2)+'    SGST: '+Number(inv.sgst).toFixed(2));doc.text('IGST: '+Number(inv.igst).toFixed(2));doc.fontSize(11).text('TOTAL AMOUNT: Rs. '+Number(inv.total).toFixed(2));doc.fontSize(9).text('Amount in words: '+words(inv.total));doc.moveDown(2).text('Certified that the particulars above are true and correct.');doc.moveDown(3).text('For '+(biz.name||'Business'),{align:'right'}).text('Authorised Signatory',{align:'right'});doc.end()}
app.get('/api/health',async(r,s)=>{try{await db.ready; s.json({ok:true})}catch(e){s.status(500).json({ok:false,error:e.message})}});
app.post('/api/auth/register',async(r,s)=>{try{await db.ready;s.status(201).json({success:true,business:await db.register(r.body.firm_id,r.body.name,r.body.password)})}catch(e){s.status(400).json({error:e.message})}});
app.post('/api/auth/login',async(r,s)=>{try{await db.ready;const x=await db.login(r.body.firm_id,r.body.password);if(!x)return s.status(401).json({error:'Invalid Firm ID or password'});s.cookieToken=x.token;s.setHeader('Set-Cookie','dm_token='+encodeURIComponent(x.token)+'; HttpOnly; Path=/; SameSite=Lax'+(process.env.NODE_ENV==='production'?'; Secure':''));s.json({success:true,csrf:x.csrf,business:x.business,user:x.user})}catch(e){s.status(500).json({error:e.message})}});
app.post('/api/auth/logout',auth,csrf,async(r,s)=>{await db.logout(cookieToken(r));s.setHeader('Set-Cookie','dm_token=; HttpOnly; Path=/; Max-Age=0; SameSite=Lax');s.json({success:true})});
app.get('/api/auth/me',auth,async(r,s)=>s.json({business:await db.business(r.businessId),user:{id:r.userId}}));
app.use('/api',auth); app.use('/api',csrf);
app.get('/api/dashboard',async(r,s)=>s.json(await db.dashboard(r.businessId)));
app.get('/api/items',async(r,s)=>s.json({items:await db.items(r.businessId)}));
app.post('/api/items',async(r,s)=>{try{s.status(201).json({item:await db.addItem(r.businessId,r.body)})}catch(e){s.status(400).json({error:e.message})}});
app.put('/api/items/:id',async(r,s)=>{try{s.json({item:await db.editItem(r.businessId,Number(r.params.id),r.body)})}catch(e){s.status(400).json({error:e.message})}});
app.post('/api/items/:id/stock',async(r,s)=>{try{s.json({item:await db.stockIn(r.businessId,Number(r.params.id),r.body.quantity,r.body.reason)})}catch(e){s.status(400).json({error:e.message})}});
app.get('/api/transactions',async(r,s)=>s.json({transactions:await db.transactions(r.businessId)}));
app.get('/api/senders',async(r,s)=>s.json({senders:await db.senders(r.businessId)})); app.post('/api/senders',async(r,s)=>{try{s.status(201).json({sender:await db.addSender(r.businessId,r.body.phone,r.body.name)})}catch(e){s.status(400).json({error:e.message})}}); app.delete('/api/senders/:id',async(r,s)=>{await db.delSender(r.businessId,Number(r.params.id));s.json({success:true})});
app.get('/api/customers',async(r,s)=>s.json({customers:await db.customers(r.businessId)})); app.post('/api/customers',async(r,s)=>{try{s.status(201).json({customer:await db.addCustomer(r.businessId,r.body)})}catch(e){s.status(400).json({error:e.message})}});
app.get('/api/orders',async(r,s)=>s.json({orders:await db.orders(r.businessId)})); app.get('/api/orders/:id',async(r,s)=>{const o=await db.order(r.businessId,Number(r.params.id));if(!o)return s.status(404).json({error:'Order not found'});s.json({order:o})});
app.get('/api/invoices',async(r,s)=>s.json({invoices:await db.invoices(r.businessId)})); app.get('/api/invoices/:id',async(r,s)=>{const i=await db.invoice(r.businessId,Number(r.params.id));if(!i)return s.status(404).json({error:'Invoice not found'});s.json({invoice:i})});
app.post('/api/invoices',async(r,s)=>{try{s.status(201).json({invoice:await db.createInvoice(r.businessId,r.body)})}catch(e){s.status(400).json({error:e.message})}}); app.post('/api/invoices/:id/finalize',async(r,s)=>{try{s.json({invoice:await db.finalizeInvoice(r.businessId,Number(r.params.id))})}catch(e){s.status(400).json({error:e.message})}}); app.post('/api/invoices/:id/cancel',async(r,s)=>{try{s.json({invoice:await db.cancelInvoice(r.businessId,Number(r.params.id))})}catch(e){s.status(400).json({error:e.message})}});
app.get('/api/invoices/:id/pdf',async(r,s)=>{const i=await db.invoice(r.businessId,Number(r.params.id)),b=await db.business(r.businessId);if(!i)return s.status(404).end();pdfInvoice(s,'invoice-'+i.invoice_no,b,i)});
app.get('/api/orders/:id/pdf',async(r,s)=>{const o=await db.order(r.businessId,Number(r.params.id)),b=await db.business(r.businessId);if(!o)return s.status(404).end();const i={invoice_no:'ORDER-'+o.id,invoice_date:o.date,customer_name:o.delivered_to,customer_address:'',customer_gstin:'',customer_state:'',place_of_supply:'',subtotal:o.items.reduce((a,x)=>a+Number(x.taxable_value||0),0),cgst:0,sgst:0,igst:o.items.reduce((a,x)=>a+Number(x.total_tax||0),0),total:o.items.reduce((a,x)=>a+Number(x.line_total||0),0),items:o.items};pdfInvoice(s,'order-'+o.id,b,i)});
app.get('/api/purchases',async(r,s)=>s.json({purchases:await db.purchaseBills(r.businessId)})); app.get('/api/purchases/:id',async(r,s)=>s.json({purchase:await db.purchase(r.businessId,Number(r.params.id))}));
app.post('/api/purchases/extract',upload.single('bill'),async(r,s)=>{try{if(!r.file)return s.status(400).json({error:'Upload a PDF or image'});const text=await extractText(r.file),parsed=parseBill(text);const existing=await db.get('SELECT id FROM purchase_bills WHERE business_id=? AND file_hash=?',[r.businessId,hash(r.file.buffer)]);if(existing)return s.status(409).json({error:'This bill file was already uploaded',purchase_id:existing.id});const id=await db.createPurchase(r.businessId,{original_filename:r.file.originalname,file_type:r.file.mimetype,file_hash:hash(r.file.buffer),...parsed});for(const x of parsed.items)await db.addPurchaseItem(r.businessId,id,x);s.json({success:true,purchase:await db.purchase(r.businessId,id),extracted:parsed})}catch(e){s.status(400).json({error:e.message})}});
app.post('/api/purchases/:id/confirm',async(r,s)=>{try{s.json({purchase:await db.confirmPurchase(r.businessId,Number(r.params.id),r.body.items||[])})}catch(e){s.status(400).json({error:e.message})}});
app.get('/api/whatsapp/status',async(r,s)=>s.json({status:await db.waStatus(r.businessId)})); app.post('/api/whatsapp/restart',async(r,s)=>{try{const worker=require('./index');await worker.startBusiness(r.businessId,true);s.json({success:true})}catch(e){s.status(400).json({error:e.message})}});
app.get('/api/settings',async(r,s)=>s.json({business:await db.business(r.businessId)})); app.put('/api/settings',async(r,s)=>s.json({business:await db.updateBusiness(r.businessId,r.body)}));
app.get('/api/orders/:id/voice',async(r,s)=>{const o=await db.order(r.businessId,Number(r.params.id));if(!o)return s.status(404).end();s.json({text:'Order '+o.id+' for '+o.delivered_to+'. '+o.items.map(x=>x.item_name+' '+x.requested_quantity).join(', ')})});
app.use((r,s)=>{if(r.path.startsWith('/api'))return s.status(404).json({error:'API route not found'});s.sendFile(path.join(PUBLIC,'index.html'))});
app.use((e,r,s,n)=>{console.error(e);if(r.path.startsWith('/api'))return s.status(500).json({error:'Server error'});s.status(500).send('Server error')});
db.ready.then(async()=>{app.listen(PORT,'0.0.0.0',()=>console.log('Delivery Management Platform running on '+PORT));try{require('./index').startAll()}catch(e){console.error('WhatsApp worker:',e)}}).catch(e=>{console.error(e);process.exit(1)});
module.exports=app;