const fs = require('fs');
const path = require('path');
const root = path.join(__dirname, '..');
const read = file => fs.readFileSync(path.join(root, file), 'utf8');
const index = read('index.js');
const database = read('database.js');
const server = read('server.js');
const app = read('public/app.js');
function must(text, pattern, message) { if (!pattern.test(text)) throw new Error(message); }
must(index, /inFlightMessageIds/, 'Missing in-flight WhatsApp duplicate guard.');
if (!index.includes('db.claimConfirmation(order.id)')) throw new Error('Missing atomic confirmation claim.');
if (!index.includes('handleStockCommand(\n                        message,\n                        WHATSAPP_BUSINESS_ID')) throw new Error('Stock command is not business-scoped.');
if (!index.includes('📦 *CURRENT STOCK*')) throw new Error('Stock reply heading was not normalized.');
must(database, /async function claimConfirmation\\(orderId\\)/, 'Missing database confirmation claim.');
must(database, /confirmation_sent = 2/, 'Missing confirmation sending state.');
if (!database.includes('Number(item.current_stock) !== 0')) throw new Error('Delete guard must require zero stock.');
must(server, /db\\.deleteItem\\(num\\(req\\.params\\.id\\), req\\.auth\\.businessId\\)/, 'Delete API is not using the guarded database method.');
if (!server.includes("COALESCE(i.name,'Deleted product #'")) throw new Error('Transaction history does not handle deleted products.');
must(app, /deleteProduct\\(x\\.id\\)/, 'Zero-stock delete button is missing.');
must(app, /Number\\(x\\.current_stock\\)===0/, 'Delete button is not restricted to zero stock.');
console.log('Static regression checks passed.');